tasks:
  - type: python-build
    package: haondt-athena
    registries:
      - testpypi
  - type: python-build
    auto:
      - source: push
    package: haondt-athena
    embed_metadata: athena/_metadata.py
    registries:
      - pypi
      - gitlab

