[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "athena"
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["version"]
dependencies = [
    "typer ~= 0.9.0",
    "pyyaml ~= 6.0.1",
    "requests ~= 2.31.0",
    "aiohttp ~= 3.8.6"
]
